<?php
function nasa_hfe_drone_popup_block() {
    return array(
        'post' => array(
            'post_title' => 'HFE Drone - Popup Block',
            'post_name' => 'hfe-drone-popup-block'
        ),
        
        'post_meta' => array(
            '_elementor_data' => '[{"id":"15639460","settings":{"layout":"full_width","background_background":"classic","background_color":"#FFFFFF","border_border":"solid","border_width":{"unit":"px","top":"1","right":"1","bottom":"1","left":"1","isLinked":true},"border_color":"#ECECEC","border_radius":{"unit":"px","top":"0","right":"0","bottom":"10","left":"10","isLinked":false}},"elements":[{"id":"138d948","settings":{"_column_size":100,"_inline_size":null,"border_color":"#FFFFFF","border_radius":{"unit":"px","top":"0","right":"0","bottom":"10","left":"10","isLinked":false},"box_shadow_box_shadow_type":"yes","box_shadow_box_shadow":{"horizontal":"","vertical":"","blur":"","spread":"","color":"rgba(4.000000000000004,29.999999999999982,66,0.07)"}},"elements":[{"id":"739327c1","settings":{"type":"recent_product","style":"carousel","arrows":"1","auto_delay_time":6,"number":7,"_padding":{"unit":"px","top":"30","right":"40","bottom":"10","left":"40","isLinked":false},"_padding_tablet":{"unit":"px","top":"20","right":"20","bottom":"10","left":"20","isLinked":false},"_padding_mobile":{"unit":"px","top":"10","right":"10","bottom":"10","left":"10","isLinked":true},"title_shortcode":"Items on sale this week","pos_nav":"top","columns_number":"5","title_font_size":"fs-20","title_dash_remove":"1","product_description":"Top picks this week. Up to 50% off the best selling products."},"elements":[],"isInner":false,"widgetType":"nasa-products","elType":"widget"}],"isInner":false,"elType":"column"}],"isInner":false,"elType":"section"}]',
            // 'ehf_template_type' => 'custom'
        ),

        'css' => '.elementor-[inserted_id] .elementor-element.elementor-element-15639460:not(.elementor-motion-effects-element-type-background), .elementor-[inserted_id] .elementor-element.elementor-element-15639460 > .elementor-motion-effects-container > .elementor-motion-effects-layer{background-color:#FFFFFF;}.elementor-[inserted_id] .elementor-element.elementor-element-15639460{border-style:solid;border-width:1px 1px 1px 1px;border-color:#ECECEC;transition:background 0.3s, border 0.3s, border-radius 0.3s, box-shadow 0.3s;}.elementor-[inserted_id] .elementor-element.elementor-element-15639460, .elementor-[inserted_id] .elementor-element.elementor-element-15639460 > .elementor-background-overlay{border-radius:0px 0px 10px 10px;}.elementor-[inserted_id] .elementor-element.elementor-element-15639460 > .elementor-background-overlay{transition:background 0.3s, border-radius 0.3s, opacity 0.3s;}.elementor-[inserted_id] .elementor-element.elementor-element-138d948 > .elementor-element-populated, .elementor-[inserted_id] .elementor-element.elementor-element-138d948 > .elementor-element-populated > .elementor-background-overlay, .elementor-[inserted_id] .elementor-element.elementor-element-138d948 > .elementor-background-slideshow{border-radius:0px 0px 10px 10px;}.elementor-[inserted_id] .elementor-element.elementor-element-739327c1 > .elementor-widget-container{padding:30px 40px 10px 40px;}@media(max-width:1024px){.elementor-[inserted_id] .elementor-element.elementor-element-739327c1 > .elementor-widget-container{padding:20px 20px 10px 20px;}}@media(max-width:767px){.elementor-[inserted_id] .elementor-element.elementor-element-739327c1 > .elementor-widget-container{padding:10px 10px 10px 10px;}}'
    );
}   
